FROM jenkins:2.7.4

MAINTAINER soo@kadaster.nl

RUN /usr/local/bin/install-plugins.sh locale \
                                      greenballs \
                                      workflow-aggregator \
                                      github-organization-folder
