println "------ Configure Maven installers ----------------------------------"
println ""
println "INFO : No Maven installers defined."
println ""
println "------ END ---------------------------------------------------------"
