println "------ Configure Maven installers -------------------------------------------"
println ""
println "ERROR: No Maven installers defined."
println ""
println "------ END ------------------------------------------------------------------"
