println "------ Configure Docker installers ---------------------------------"
println ""
println "ERROR: No Docker installers defined."
println ""
println "------ END ---------------------------------------------------------"
