println "------ Configure Docker installers ---------------------------------"
println ""
println "INFO : No Docker installers defined."
println ""
println "------ END ---------------------------------------------------------"
